// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file customer.proto (package customer, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file customer.proto.
 */
export const file_customer: GenFile = /*@__PURE__*/
  fileDesc("Cg5jdXN0b21lci5wcm90bxIIY3VzdG9tZXIiNgoVQ3JlYXRlQ3VzdG9tZXJSZXF1ZXN0EgwKBG5hbWUYASABKAkSDwoHc3VybmFtZRgCIAEoCSIkChZDcmVhdGVDdXN0b21lclJlc3BvbnNlEgoKAmlkGAEgASgDIjUKE0dldEN1c3RvbWVyc1JlcXVlc3QSDAoEcGFnZRgBIAEoAxIQCghwYWdlU2l6ZRgCIAEoAyJMChRHZXRDdXN0b21lcnNSZXNwb25zZRINCgV0b3RhbBgBIAEoAxIlCgVpdGVtcxgCIAMoCzIWLmN1c3RvbWVyLkN1c3RvbWVySXRlbSI5CgxDdXN0b21lckl0ZW0SCgoCaWQYASABKAMSDAoEbmFtZRgDIAEoCRIPCgdzdXJuYW1lGAQgASgJIiAKEkdldEN1c3RvbWVyUmVxdWVzdBIKCgJpZBgBIAEoAyJAChNHZXRDdXN0b21lclJlc3BvbnNlEgoKAmlkGAEgASgDEgwKBG5hbWUYAiABKAkSDwoHc3VybmFtZRgDIAEoCTKFAgoPQ3VzdG9tZXJTZXJ2aWNlElMKDkNyZWF0ZUN1c3RvbWVyEh8uY3VzdG9tZXIuQ3JlYXRlQ3VzdG9tZXJSZXF1ZXN0GiAuY3VzdG9tZXIuQ3JlYXRlQ3VzdG9tZXJSZXNwb25zZRJNCgxHZXRDdXN0b21lcnMSHS5jdXN0b21lci5HZXRDdXN0b21lcnNSZXF1ZXN0Gh4uY3VzdG9tZXIuR2V0Q3VzdG9tZXJzUmVzcG9uc2USTgoPR2V0Q3VzdG9tZXJCeUlkEhwuY3VzdG9tZXIuR2V0Q3VzdG9tZXJSZXF1ZXN0Gh0uY3VzdG9tZXIuR2V0Q3VzdG9tZXJSZXNwb25zZUIqWihnaXRodWIuY29tL21hZ29tZWRjb2Rlci9pcG1hbmFnZXIvYXBpL3BiYgZwcm90bzM");

/**
 * @generated from message customer.CreateCustomerRequest
 */
export type CreateCustomerRequest = Message<"customer.CreateCustomerRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string surname = 2;
   */
  surname: string;
};

/**
 * Describes the message customer.CreateCustomerRequest.
 * Use `create(CreateCustomerRequestSchema)` to create a new message.
 */
export const CreateCustomerRequestSchema: GenMessage<CreateCustomerRequest> = /*@__PURE__*/
  messageDesc(file_customer, 0);

/**
 * @generated from message customer.CreateCustomerResponse
 */
export type CreateCustomerResponse = Message<"customer.CreateCustomerResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message customer.CreateCustomerResponse.
 * Use `create(CreateCustomerResponseSchema)` to create a new message.
 */
export const CreateCustomerResponseSchema: GenMessage<CreateCustomerResponse> = /*@__PURE__*/
  messageDesc(file_customer, 1);

/**
 * @generated from message customer.GetCustomersRequest
 */
export type GetCustomersRequest = Message<"customer.GetCustomersRequest"> & {
  /**
   * @generated from field: int64 page = 1;
   */
  page: bigint;

  /**
   * @generated from field: int64 pageSize = 2;
   */
  pageSize: bigint;
};

/**
 * Describes the message customer.GetCustomersRequest.
 * Use `create(GetCustomersRequestSchema)` to create a new message.
 */
export const GetCustomersRequestSchema: GenMessage<GetCustomersRequest> = /*@__PURE__*/
  messageDesc(file_customer, 2);

/**
 * @generated from message customer.GetCustomersResponse
 */
export type GetCustomersResponse = Message<"customer.GetCustomersResponse"> & {
  /**
   * @generated from field: int64 total = 1;
   */
  total: bigint;

  /**
   * @generated from field: repeated customer.CustomerItem items = 2;
   */
  items: CustomerItem[];
};

/**
 * Describes the message customer.GetCustomersResponse.
 * Use `create(GetCustomersResponseSchema)` to create a new message.
 */
export const GetCustomersResponseSchema: GenMessage<GetCustomersResponse> = /*@__PURE__*/
  messageDesc(file_customer, 3);

/**
 * @generated from message customer.CustomerItem
 */
export type CustomerItem = Message<"customer.CustomerItem"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 3;
   */
  name: string;

  /**
   * @generated from field: string surname = 4;
   */
  surname: string;
};

/**
 * Describes the message customer.CustomerItem.
 * Use `create(CustomerItemSchema)` to create a new message.
 */
export const CustomerItemSchema: GenMessage<CustomerItem> = /*@__PURE__*/
  messageDesc(file_customer, 4);

/**
 * @generated from message customer.GetCustomerRequest
 */
export type GetCustomerRequest = Message<"customer.GetCustomerRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message customer.GetCustomerRequest.
 * Use `create(GetCustomerRequestSchema)` to create a new message.
 */
export const GetCustomerRequestSchema: GenMessage<GetCustomerRequest> = /*@__PURE__*/
  messageDesc(file_customer, 5);

/**
 * @generated from message customer.GetCustomerResponse
 */
export type GetCustomerResponse = Message<"customer.GetCustomerResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string surname = 3;
   */
  surname: string;
};

/**
 * Describes the message customer.GetCustomerResponse.
 * Use `create(GetCustomerResponseSchema)` to create a new message.
 */
export const GetCustomerResponseSchema: GenMessage<GetCustomerResponse> = /*@__PURE__*/
  messageDesc(file_customer, 6);

/**
 * @generated from service customer.CustomerService
 */
export const CustomerService: GenService<{
  /**
   * @generated from rpc customer.CustomerService.CreateCustomer
   */
  createCustomer: {
    methodKind: "unary";
    input: typeof CreateCustomerRequestSchema;
    output: typeof CreateCustomerResponseSchema;
  },
  /**
   * @generated from rpc customer.CustomerService.GetCustomers
   */
  getCustomers: {
    methodKind: "unary";
    input: typeof GetCustomersRequestSchema;
    output: typeof GetCustomersResponseSchema;
  },
  /**
   * @generated from rpc customer.CustomerService.GetCustomerById
   */
  getCustomerById: {
    methodKind: "unary";
    input: typeof GetCustomerRequestSchema;
    output: typeof GetCustomerResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_customer, 0);

