// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file ip.proto (package ip, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ip.proto.
 */
export const file_ip: GenFile = /*@__PURE__*/
  fileDesc("CghpcC5wcm90bxICaXAiIgoNR2V0SXBzUmVxdWVzdBIRCglzdWJuZXRfaWQYASABKAMiOgoOR2V0SXBzUmVzcG9uc2USDQoFdG90YWwYASABKAMSGQoFaXRlbXMYAiADKAsyCi5pcC5JcEl0ZW0imQEKBklwSXRlbRIKCgJpZBgBIAEoAxIKCgJpcBgCIAEoCRIMCgRidXN5GAMgASgIEhMKC2N1c3RvbWVyX2lkGAQgASgDEhUKDWN1c3RvbWVyX25hbWUYBSABKAkSEgoKc2VydmljZV9pZBgGIAEoAxIUCgxzZXJ2aWNlX25hbWUYByABKAkSEwoLZGVzY3JpcHRpb24YCCABKAkiGgoMR2V0SXBSZXF1ZXN0EgoKAmlkGAEgASgDIqABCg1HZXRJcFJlc3BvbnNlEgoKAmlkGAEgASgDEgoKAmlwGAIgASgJEgwKBGJ1c3kYAyABKAgSEwoLY3VzdG9tZXJfaWQYBCABKAMSFQoNY3VzdG9tZXJfbmFtZRgFIAEoCRISCgpzZXJ2aWNlX2lkGAYgASgDEhQKDHNlcnZpY2VfbmFtZRgHIAEoCRITCgtkZXNjcmlwdGlvbhgIIAEoCSI4ChVFZGl0SXBDdXN0b21lclJlcXVlc3QSCgoCaWQYASABKAMSEwoLY3VzdG9tZXJfaWQYAiABKAMiKQoWRWRpdElwQ3VzdG9tZXJSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIIjYKFEVkaXRJcFNlcnZpY2VSZXF1ZXN0EgoKAmlkGAEgASgDEhIKCnNlcnZpY2VfaWQYAiABKAMiKAoVRWRpdElwU2VydmljZVJlc3BvbnNlEg8KB3N1Y2Nlc3MYASABKAgiOwoYRWRpdElwRGVzY3JpcHRpb25SZXF1ZXN0EgoKAmlkGAEgASgDEhMKC2Rlc2NyaXB0aW9uGAIgASgJIiwKGUVkaXRJcERlc2NyaXB0aW9uUmVzcG9uc2USDwoHc3VjY2VzcxgBIAEoCDLPAgoJSXBTZXJ2aWNlEi8KBkdldElwcxIRLmlwLkdldElwc1JlcXVlc3QaEi5pcC5HZXRJcHNSZXNwb25zZRIwCglHZXRJcEJ5SWQSEC5pcC5HZXRJcFJlcXVlc3QaES5pcC5HZXRJcFJlc3BvbnNlEkcKDkVkaXRJcEN1c3RvbWVyEhkuaXAuRWRpdElwQ3VzdG9tZXJSZXF1ZXN0GhouaXAuRWRpdElwQ3VzdG9tZXJSZXNwb25zZRJECg1FZGl0SXBTZXJ2aWNlEhguaXAuRWRpdElwU2VydmljZVJlcXVlc3QaGS5pcC5FZGl0SXBTZXJ2aWNlUmVzcG9uc2USUAoRRWRpdElwRGVzY3JpcHRpb24SHC5pcC5FZGl0SXBEZXNjcmlwdGlvblJlcXVlc3QaHS5pcC5FZGl0SXBEZXNjcmlwdGlvblJlc3BvbnNlQipaKGdpdGh1Yi5jb20vbWFnb21lZGNvZGVyL2lwbWFuYWdlci9hcGkvcGJiBnByb3RvMw");

/**
 * @generated from message ip.GetIpsRequest
 */
export type GetIpsRequest = Message<"ip.GetIpsRequest"> & {
  /**
   * @generated from field: int64 subnet_id = 1;
   */
  subnetId: bigint;
};

/**
 * Describes the message ip.GetIpsRequest.
 * Use `create(GetIpsRequestSchema)` to create a new message.
 */
export const GetIpsRequestSchema: GenMessage<GetIpsRequest> = /*@__PURE__*/
  messageDesc(file_ip, 0);

/**
 * @generated from message ip.GetIpsResponse
 */
export type GetIpsResponse = Message<"ip.GetIpsResponse"> & {
  /**
   * @generated from field: int64 total = 1;
   */
  total: bigint;

  /**
   * @generated from field: repeated ip.IpItem items = 2;
   */
  items: IpItem[];
};

/**
 * Describes the message ip.GetIpsResponse.
 * Use `create(GetIpsResponseSchema)` to create a new message.
 */
export const GetIpsResponseSchema: GenMessage<GetIpsResponse> = /*@__PURE__*/
  messageDesc(file_ip, 1);

/**
 * @generated from message ip.IpItem
 */
export type IpItem = Message<"ip.IpItem"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string ip = 2;
   */
  ip: string;

  /**
   * @generated from field: bool busy = 3;
   */
  busy: boolean;

  /**
   * @generated from field: int64 customer_id = 4;
   */
  customerId: bigint;

  /**
   * @generated from field: string customer_name = 5;
   */
  customerName: string;

  /**
   * @generated from field: int64 service_id = 6;
   */
  serviceId: bigint;

  /**
   * @generated from field: string service_name = 7;
   */
  serviceName: string;

  /**
   * @generated from field: string description = 8;
   */
  description: string;
};

/**
 * Describes the message ip.IpItem.
 * Use `create(IpItemSchema)` to create a new message.
 */
export const IpItemSchema: GenMessage<IpItem> = /*@__PURE__*/
  messageDesc(file_ip, 2);

/**
 * @generated from message ip.GetIpRequest
 */
export type GetIpRequest = Message<"ip.GetIpRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message ip.GetIpRequest.
 * Use `create(GetIpRequestSchema)` to create a new message.
 */
export const GetIpRequestSchema: GenMessage<GetIpRequest> = /*@__PURE__*/
  messageDesc(file_ip, 3);

/**
 * @generated from message ip.GetIpResponse
 */
export type GetIpResponse = Message<"ip.GetIpResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string ip = 2;
   */
  ip: string;

  /**
   * @generated from field: bool busy = 3;
   */
  busy: boolean;

  /**
   * @generated from field: int64 customer_id = 4;
   */
  customerId: bigint;

  /**
   * @generated from field: string customer_name = 5;
   */
  customerName: string;

  /**
   * @generated from field: int64 service_id = 6;
   */
  serviceId: bigint;

  /**
   * @generated from field: string service_name = 7;
   */
  serviceName: string;

  /**
   * @generated from field: string description = 8;
   */
  description: string;
};

/**
 * Describes the message ip.GetIpResponse.
 * Use `create(GetIpResponseSchema)` to create a new message.
 */
export const GetIpResponseSchema: GenMessage<GetIpResponse> = /*@__PURE__*/
  messageDesc(file_ip, 4);

/**
 * @generated from message ip.EditIpCustomerRequest
 */
export type EditIpCustomerRequest = Message<"ip.EditIpCustomerRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int64 customer_id = 2;
   */
  customerId: bigint;
};

/**
 * Describes the message ip.EditIpCustomerRequest.
 * Use `create(EditIpCustomerRequestSchema)` to create a new message.
 */
export const EditIpCustomerRequestSchema: GenMessage<EditIpCustomerRequest> = /*@__PURE__*/
  messageDesc(file_ip, 5);

/**
 * @generated from message ip.EditIpCustomerResponse
 */
export type EditIpCustomerResponse = Message<"ip.EditIpCustomerResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message ip.EditIpCustomerResponse.
 * Use `create(EditIpCustomerResponseSchema)` to create a new message.
 */
export const EditIpCustomerResponseSchema: GenMessage<EditIpCustomerResponse> = /*@__PURE__*/
  messageDesc(file_ip, 6);

/**
 * @generated from message ip.EditIpServiceRequest
 */
export type EditIpServiceRequest = Message<"ip.EditIpServiceRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: int64 service_id = 2;
   */
  serviceId: bigint;
};

/**
 * Describes the message ip.EditIpServiceRequest.
 * Use `create(EditIpServiceRequestSchema)` to create a new message.
 */
export const EditIpServiceRequestSchema: GenMessage<EditIpServiceRequest> = /*@__PURE__*/
  messageDesc(file_ip, 7);

/**
 * @generated from message ip.EditIpServiceResponse
 */
export type EditIpServiceResponse = Message<"ip.EditIpServiceResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message ip.EditIpServiceResponse.
 * Use `create(EditIpServiceResponseSchema)` to create a new message.
 */
export const EditIpServiceResponseSchema: GenMessage<EditIpServiceResponse> = /*@__PURE__*/
  messageDesc(file_ip, 8);

/**
 * @generated from message ip.EditIpDescriptionRequest
 */
export type EditIpDescriptionRequest = Message<"ip.EditIpDescriptionRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string description = 2;
   */
  description: string;
};

/**
 * Describes the message ip.EditIpDescriptionRequest.
 * Use `create(EditIpDescriptionRequestSchema)` to create a new message.
 */
export const EditIpDescriptionRequestSchema: GenMessage<EditIpDescriptionRequest> = /*@__PURE__*/
  messageDesc(file_ip, 9);

/**
 * @generated from message ip.EditIpDescriptionResponse
 */
export type EditIpDescriptionResponse = Message<"ip.EditIpDescriptionResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message ip.EditIpDescriptionResponse.
 * Use `create(EditIpDescriptionResponseSchema)` to create a new message.
 */
export const EditIpDescriptionResponseSchema: GenMessage<EditIpDescriptionResponse> = /*@__PURE__*/
  messageDesc(file_ip, 10);

/**
 * @generated from service ip.IpService
 */
export const IpService: GenService<{
  /**
   * @generated from rpc ip.IpService.GetIps
   */
  getIps: {
    methodKind: "unary";
    input: typeof GetIpsRequestSchema;
    output: typeof GetIpsResponseSchema;
  },
  /**
   * @generated from rpc ip.IpService.GetIpById
   */
  getIpById: {
    methodKind: "unary";
    input: typeof GetIpRequestSchema;
    output: typeof GetIpResponseSchema;
  },
  /**
   * @generated from rpc ip.IpService.EditIpCustomer
   */
  editIpCustomer: {
    methodKind: "unary";
    input: typeof EditIpCustomerRequestSchema;
    output: typeof EditIpCustomerResponseSchema;
  },
  /**
   * @generated from rpc ip.IpService.EditIpService
   */
  editIpService: {
    methodKind: "unary";
    input: typeof EditIpServiceRequestSchema;
    output: typeof EditIpServiceResponseSchema;
  },
  /**
   * @generated from rpc ip.IpService.EditIpDescription
   */
  editIpDescription: {
    methodKind: "unary";
    input: typeof EditIpDescriptionRequestSchema;
    output: typeof EditIpDescriptionResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_ip, 0);

