// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file service.proto (package service, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file service.proto.
 */
export const file_service: GenFile = /*@__PURE__*/
  fileDesc("Cg1zZXJ2aWNlLnByb3RvEgdzZXJ2aWNlIiQKFENyZWF0ZVNlcnZpY2VSZXF1ZXN0EgwKBG5hbWUYASABKAkiIwoVQ3JlYXRlU2VydmljZVJlc3BvbnNlEgoKAmlkGAEgASgDIjQKEkdldFNlcnZpY2VzUmVxdWVzdBIMCgRwYWdlGAEgASgDEhAKCHBhZ2VTaXplGAIgASgDIkkKE0dldFNlcnZpY2VzUmVzcG9uc2USDQoFdG90YWwYASABKAMSIwoFaXRlbXMYAiADKAsyFC5zZXJ2aWNlLlNlcnZpY2VJdGVtIicKC1NlcnZpY2VWbGFuEgoKAmlkGAEgASgDEgwKBG5hbWUYAiABKAkiIwoJU2VydmljZUlwEgoKAmlkGAEgASgDEgoKAmlwGAIgASgJIm0KC1NlcnZpY2VJdGVtEgoKAmlkGAEgASgDEgwKBG5hbWUYAiABKAkSIwoFdmxhbnMYAyADKAsyFC5zZXJ2aWNlLlNlcnZpY2VWbGFuEh8KA2lwcxgEIAMoCzISLnNlcnZpY2UuU2VydmljZUlwIh8KEUdldFNlcnZpY2VSZXF1ZXN0EgoKAmlkGAEgASgDInQKEkdldFNlcnZpY2VSZXNwb25zZRIKCgJpZBgBIAEoAxIMCgRuYW1lGAIgASgJEiMKBXZsYW5zGAMgAygLMhQuc2VydmljZS5TZXJ2aWNlVmxhbhIfCgNpcHMYBCADKAsyEi5zZXJ2aWNlLlNlcnZpY2VJcDL1AQoOU2VydmljZVNlcnZpY2USTgoNQ3JlYXRlU2VydmljZRIdLnNlcnZpY2UuQ3JlYXRlU2VydmljZVJlcXVlc3QaHi5zZXJ2aWNlLkNyZWF0ZVNlcnZpY2VSZXNwb25zZRJICgtHZXRTZXJ2aWNlcxIbLnNlcnZpY2UuR2V0U2VydmljZXNSZXF1ZXN0Ghwuc2VydmljZS5HZXRTZXJ2aWNlc1Jlc3BvbnNlEkkKDkdldFNlcnZpY2VCeUlkEhouc2VydmljZS5HZXRTZXJ2aWNlUmVxdWVzdBobLnNlcnZpY2UuR2V0U2VydmljZVJlc3BvbnNlQipaKGdpdGh1Yi5jb20vbWFnb21lZGNvZGVyL2lwbWFuYWdlci9hcGkvcGJiBnByb3RvMw");

/**
 * @generated from message service.CreateServiceRequest
 */
export type CreateServiceRequest = Message<"service.CreateServiceRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message service.CreateServiceRequest.
 * Use `create(CreateServiceRequestSchema)` to create a new message.
 */
export const CreateServiceRequestSchema: GenMessage<CreateServiceRequest> = /*@__PURE__*/
  messageDesc(file_service, 0);

/**
 * @generated from message service.CreateServiceResponse
 */
export type CreateServiceResponse = Message<"service.CreateServiceResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message service.CreateServiceResponse.
 * Use `create(CreateServiceResponseSchema)` to create a new message.
 */
export const CreateServiceResponseSchema: GenMessage<CreateServiceResponse> = /*@__PURE__*/
  messageDesc(file_service, 1);

/**
 * @generated from message service.GetServicesRequest
 */
export type GetServicesRequest = Message<"service.GetServicesRequest"> & {
  /**
   * @generated from field: int64 page = 1;
   */
  page: bigint;

  /**
   * @generated from field: int64 pageSize = 2;
   */
  pageSize: bigint;
};

/**
 * Describes the message service.GetServicesRequest.
 * Use `create(GetServicesRequestSchema)` to create a new message.
 */
export const GetServicesRequestSchema: GenMessage<GetServicesRequest> = /*@__PURE__*/
  messageDesc(file_service, 2);

/**
 * @generated from message service.GetServicesResponse
 */
export type GetServicesResponse = Message<"service.GetServicesResponse"> & {
  /**
   * @generated from field: int64 total = 1;
   */
  total: bigint;

  /**
   * @generated from field: repeated service.ServiceItem items = 2;
   */
  items: ServiceItem[];
};

/**
 * Describes the message service.GetServicesResponse.
 * Use `create(GetServicesResponseSchema)` to create a new message.
 */
export const GetServicesResponseSchema: GenMessage<GetServicesResponse> = /*@__PURE__*/
  messageDesc(file_service, 3);

/**
 * @generated from message service.ServiceVlan
 */
export type ServiceVlan = Message<"service.ServiceVlan"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message service.ServiceVlan.
 * Use `create(ServiceVlanSchema)` to create a new message.
 */
export const ServiceVlanSchema: GenMessage<ServiceVlan> = /*@__PURE__*/
  messageDesc(file_service, 4);

/**
 * @generated from message service.ServiceIp
 */
export type ServiceIp = Message<"service.ServiceIp"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string ip = 2;
   */
  ip: string;
};

/**
 * Describes the message service.ServiceIp.
 * Use `create(ServiceIpSchema)` to create a new message.
 */
export const ServiceIpSchema: GenMessage<ServiceIp> = /*@__PURE__*/
  messageDesc(file_service, 5);

/**
 * @generated from message service.ServiceItem
 */
export type ServiceItem = Message<"service.ServiceItem"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated service.ServiceVlan vlans = 3;
   */
  vlans: ServiceVlan[];

  /**
   * @generated from field: repeated service.ServiceIp ips = 4;
   */
  ips: ServiceIp[];
};

/**
 * Describes the message service.ServiceItem.
 * Use `create(ServiceItemSchema)` to create a new message.
 */
export const ServiceItemSchema: GenMessage<ServiceItem> = /*@__PURE__*/
  messageDesc(file_service, 6);

/**
 * @generated from message service.GetServiceRequest
 */
export type GetServiceRequest = Message<"service.GetServiceRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message service.GetServiceRequest.
 * Use `create(GetServiceRequestSchema)` to create a new message.
 */
export const GetServiceRequestSchema: GenMessage<GetServiceRequest> = /*@__PURE__*/
  messageDesc(file_service, 7);

/**
 * @generated from message service.GetServiceResponse
 */
export type GetServiceResponse = Message<"service.GetServiceResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: repeated service.ServiceVlan vlans = 3;
   */
  vlans: ServiceVlan[];

  /**
   * @generated from field: repeated service.ServiceIp ips = 4;
   */
  ips: ServiceIp[];
};

/**
 * Describes the message service.GetServiceResponse.
 * Use `create(GetServiceResponseSchema)` to create a new message.
 */
export const GetServiceResponseSchema: GenMessage<GetServiceResponse> = /*@__PURE__*/
  messageDesc(file_service, 8);

/**
 * @generated from service service.ServiceService
 */
export const ServiceService: GenService<{
  /**
   * @generated from rpc service.ServiceService.CreateService
   */
  createService: {
    methodKind: "unary";
    input: typeof CreateServiceRequestSchema;
    output: typeof CreateServiceResponseSchema;
  },
  /**
   * @generated from rpc service.ServiceService.GetServices
   */
  getServices: {
    methodKind: "unary";
    input: typeof GetServicesRequestSchema;
    output: typeof GetServicesResponseSchema;
  },
  /**
   * @generated from rpc service.ServiceService.GetServiceById
   */
  getServiceById: {
    methodKind: "unary";
    input: typeof GetServiceRequestSchema;
    output: typeof GetServiceResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_service, 0);

