// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file user.proto (package user, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file user.proto.
 */
export const file_user: GenFile = /*@__PURE__*/
  fileDesc("Cgp1c2VyLnByb3RvEgR1c2VyIjYKEFVzZXJMb2dpblJlcXVlc3QSEAoIdXNlcm5hbWUYASABKAkSEAoIcGFzc3dvcmQYAiABKAkiKQoRVXNlckxvZ2luUmVzcG9uc2USFAoMYWNjZXNzX3Rva2VuGAEgASgJIhMKEVVzZXJMb2dvdXRSZXF1ZXN0IiUKElVzZXJMb2dvdXRSZXNwb25zZRIPCgdzdWNjZXNzGAEgASgIMoQBCgtVc2VyU2VydmljZRI4CgVMb2dpbhIWLnVzZXIuVXNlckxvZ2luUmVxdWVzdBoXLnVzZXIuVXNlckxvZ2luUmVzcG9uc2USOwoGTG9nb3V0EhcudXNlci5Vc2VyTG9nb3V0UmVxdWVzdBoYLnVzZXIuVXNlckxvZ291dFJlc3BvbnNlQipaKGdpdGh1Yi5jb20vbWFnb21lZGNvZGVyL2lwbWFuYWdlci9hcGkvcGJiBnByb3RvMw");

/**
 * @generated from message user.UserLoginRequest
 */
export type UserLoginRequest = Message<"user.UserLoginRequest"> & {
  /**
   * @generated from field: string username = 1;
   */
  username: string;

  /**
   * @generated from field: string password = 2;
   */
  password: string;
};

/**
 * Describes the message user.UserLoginRequest.
 * Use `create(UserLoginRequestSchema)` to create a new message.
 */
export const UserLoginRequestSchema: GenMessage<UserLoginRequest> = /*@__PURE__*/
  messageDesc(file_user, 0);

/**
 * @generated from message user.UserLoginResponse
 */
export type UserLoginResponse = Message<"user.UserLoginResponse"> & {
  /**
   * @generated from field: string access_token = 1;
   */
  accessToken: string;
};

/**
 * Describes the message user.UserLoginResponse.
 * Use `create(UserLoginResponseSchema)` to create a new message.
 */
export const UserLoginResponseSchema: GenMessage<UserLoginResponse> = /*@__PURE__*/
  messageDesc(file_user, 1);

/**
 * @generated from message user.UserLogoutRequest
 */
export type UserLogoutRequest = Message<"user.UserLogoutRequest"> & {
};

/**
 * Describes the message user.UserLogoutRequest.
 * Use `create(UserLogoutRequestSchema)` to create a new message.
 */
export const UserLogoutRequestSchema: GenMessage<UserLogoutRequest> = /*@__PURE__*/
  messageDesc(file_user, 2);

/**
 * @generated from message user.UserLogoutResponse
 */
export type UserLogoutResponse = Message<"user.UserLogoutResponse"> & {
  /**
   * @generated from field: bool success = 1;
   */
  success: boolean;
};

/**
 * Describes the message user.UserLogoutResponse.
 * Use `create(UserLogoutResponseSchema)` to create a new message.
 */
export const UserLogoutResponseSchema: GenMessage<UserLogoutResponse> = /*@__PURE__*/
  messageDesc(file_user, 3);

/**
 * @generated from service user.UserService
 */
export const UserService: GenService<{
  /**
   * @generated from rpc user.UserService.Login
   */
  login: {
    methodKind: "unary";
    input: typeof UserLoginRequestSchema;
    output: typeof UserLoginResponseSchema;
  },
  /**
   * @generated from rpc user.UserService.Logout
   */
  logout: {
    methodKind: "unary";
    input: typeof UserLogoutRequestSchema;
    output: typeof UserLogoutResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_user, 0);

