// @generated by protoc-gen-es v2.4.0 with parameter "target=ts"
// @generated from file vlan.proto (package vlan, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv1";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file vlan.proto.
 */
export const file_vlan: GenFile = /*@__PURE__*/
  fileDesc("Cgp2bGFuLnByb3RvEgR2bGFuIiEKEUNyZWF0ZVZsYW5SZXF1ZXN0EgwKBG5hbWUYASABKAkiIAoSQ3JlYXRlVmxhblJlc3BvbnNlEgoKAmlkGAEgASgDIjEKD0dldFZsYW5zUmVxdWVzdBIMCgRwYWdlGAEgASgDEhAKCHBhZ2VTaXplGAIgASgDIkAKEEdldFZsYW5zUmVzcG9uc2USDQoFdG90YWwYASABKAMSHQoFaXRlbXMYAiADKAsyDi52bGFuLlZsYW5JdGVtIiQKCFZsYW5JdGVtEgoKAmlkGAEgASgDEgwKBG5hbWUYAiABKAkiHAoOR2V0VmxhblJlcXVlc3QSCgoCaWQYASABKAMiKwoPR2V0VmxhblJlc3BvbnNlEgoKAmlkGAEgASgDEgwKBG5hbWUYAiABKAkyxQEKC1ZsYW5TZXJ2aWNlEj8KCkNyZWF0ZVZsYW4SFy52bGFuLkNyZWF0ZVZsYW5SZXF1ZXN0Ghgudmxhbi5DcmVhdGVWbGFuUmVzcG9uc2USOQoIR2V0VmxhbnMSFS52bGFuLkdldFZsYW5zUmVxdWVzdBoWLnZsYW4uR2V0VmxhbnNSZXNwb25zZRI6CgtHZXRWbGFuQnlJZBIULnZsYW4uR2V0VmxhblJlcXVlc3QaFS52bGFuLkdldFZsYW5SZXNwb25zZUIqWihnaXRodWIuY29tL21hZ29tZWRjb2Rlci9pcG1hbmFnZXIvYXBpL3BiYgZwcm90bzM");

/**
 * @generated from message vlan.CreateVlanRequest
 */
export type CreateVlanRequest = Message<"vlan.CreateVlanRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;
};

/**
 * Describes the message vlan.CreateVlanRequest.
 * Use `create(CreateVlanRequestSchema)` to create a new message.
 */
export const CreateVlanRequestSchema: GenMessage<CreateVlanRequest> = /*@__PURE__*/
  messageDesc(file_vlan, 0);

/**
 * @generated from message vlan.CreateVlanResponse
 */
export type CreateVlanResponse = Message<"vlan.CreateVlanResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message vlan.CreateVlanResponse.
 * Use `create(CreateVlanResponseSchema)` to create a new message.
 */
export const CreateVlanResponseSchema: GenMessage<CreateVlanResponse> = /*@__PURE__*/
  messageDesc(file_vlan, 1);

/**
 * @generated from message vlan.GetVlansRequest
 */
export type GetVlansRequest = Message<"vlan.GetVlansRequest"> & {
  /**
   * @generated from field: int64 page = 1;
   */
  page: bigint;

  /**
   * @generated from field: int64 pageSize = 2;
   */
  pageSize: bigint;
};

/**
 * Describes the message vlan.GetVlansRequest.
 * Use `create(GetVlansRequestSchema)` to create a new message.
 */
export const GetVlansRequestSchema: GenMessage<GetVlansRequest> = /*@__PURE__*/
  messageDesc(file_vlan, 2);

/**
 * @generated from message vlan.GetVlansResponse
 */
export type GetVlansResponse = Message<"vlan.GetVlansResponse"> & {
  /**
   * @generated from field: int64 total = 1;
   */
  total: bigint;

  /**
   * @generated from field: repeated vlan.VlanItem items = 2;
   */
  items: VlanItem[];
};

/**
 * Describes the message vlan.GetVlansResponse.
 * Use `create(GetVlansResponseSchema)` to create a new message.
 */
export const GetVlansResponseSchema: GenMessage<GetVlansResponse> = /*@__PURE__*/
  messageDesc(file_vlan, 3);

/**
 * @generated from message vlan.VlanItem
 */
export type VlanItem = Message<"vlan.VlanItem"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message vlan.VlanItem.
 * Use `create(VlanItemSchema)` to create a new message.
 */
export const VlanItemSchema: GenMessage<VlanItem> = /*@__PURE__*/
  messageDesc(file_vlan, 4);

/**
 * @generated from message vlan.GetVlanRequest
 */
export type GetVlanRequest = Message<"vlan.GetVlanRequest"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;
};

/**
 * Describes the message vlan.GetVlanRequest.
 * Use `create(GetVlanRequestSchema)` to create a new message.
 */
export const GetVlanRequestSchema: GenMessage<GetVlanRequest> = /*@__PURE__*/
  messageDesc(file_vlan, 5);

/**
 * @generated from message vlan.GetVlanResponse
 */
export type GetVlanResponse = Message<"vlan.GetVlanResponse"> & {
  /**
   * @generated from field: int64 id = 1;
   */
  id: bigint;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message vlan.GetVlanResponse.
 * Use `create(GetVlanResponseSchema)` to create a new message.
 */
export const GetVlanResponseSchema: GenMessage<GetVlanResponse> = /*@__PURE__*/
  messageDesc(file_vlan, 6);

/**
 * @generated from service vlan.VlanService
 */
export const VlanService: GenService<{
  /**
   * @generated from rpc vlan.VlanService.CreateVlan
   */
  createVlan: {
    methodKind: "unary";
    input: typeof CreateVlanRequestSchema;
    output: typeof CreateVlanResponseSchema;
  },
  /**
   * @generated from rpc vlan.VlanService.GetVlans
   */
  getVlans: {
    methodKind: "unary";
    input: typeof GetVlansRequestSchema;
    output: typeof GetVlansResponseSchema;
  },
  /**
   * @generated from rpc vlan.VlanService.GetVlanById
   */
  getVlanById: {
    methodKind: "unary";
    input: typeof GetVlanRequestSchema;
    output: typeof GetVlanResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_vlan, 0);

