// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: ip.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IpService_CreateIp_FullMethodName = "/ip.IpService/CreateIp"
	IpService_GetIps_FullMethodName   = "/ip.IpService/GetIps"
	IpService_GetIp_FullMethodName    = "/ip.IpService/GetIp"
)

// IpServiceClient is the client API for IpService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type IpServiceClient interface {
	CreateIp(ctx context.Context, in *CreateIpRequest, opts ...grpc.CallOption) (*CreateIpResponse, error)
	GetIps(ctx context.Context, in *GetIpsRequest, opts ...grpc.CallOption) (*GetIpsResponse, error)
	GetIp(ctx context.Context, in *GetIpRequest, opts ...grpc.CallOption) (*GetIpResponse, error)
}

type ipServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIpServiceClient(cc grpc.ClientConnInterface) IpServiceClient {
	return &ipServiceClient{cc}
}

func (c *ipServiceClient) CreateIp(ctx context.Context, in *CreateIpRequest, opts ...grpc.CallOption) (*CreateIpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIpResponse)
	err := c.cc.Invoke(ctx, IpService_CreateIp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipServiceClient) GetIps(ctx context.Context, in *GetIpsRequest, opts ...grpc.CallOption) (*GetIpsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIpsResponse)
	err := c.cc.Invoke(ctx, IpService_GetIps_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *ipServiceClient) GetIp(ctx context.Context, in *GetIpRequest, opts ...grpc.CallOption) (*GetIpResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIpResponse)
	err := c.cc.Invoke(ctx, IpService_GetIp_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IpServiceServer is the server API for IpService service.
// All implementations must embed UnimplementedIpServiceServer
// for forward compatibility.
type IpServiceServer interface {
	CreateIp(context.Context, *CreateIpRequest) (*CreateIpResponse, error)
	GetIps(context.Context, *GetIpsRequest) (*GetIpsResponse, error)
	GetIp(context.Context, *GetIpRequest) (*GetIpResponse, error)
	mustEmbedUnimplementedIpServiceServer()
}

// UnimplementedIpServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIpServiceServer struct{}

func (UnimplementedIpServiceServer) CreateIp(context.Context, *CreateIpRequest) (*CreateIpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIp not implemented")
}
func (UnimplementedIpServiceServer) GetIps(context.Context, *GetIpsRequest) (*GetIpsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIps not implemented")
}
func (UnimplementedIpServiceServer) GetIp(context.Context, *GetIpRequest) (*GetIpResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetIp not implemented")
}
func (UnimplementedIpServiceServer) mustEmbedUnimplementedIpServiceServer() {}
func (UnimplementedIpServiceServer) testEmbeddedByValue()                   {}

// UnsafeIpServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IpServiceServer will
// result in compilation errors.
type UnsafeIpServiceServer interface {
	mustEmbedUnimplementedIpServiceServer()
}

func RegisterIpServiceServer(s grpc.ServiceRegistrar, srv IpServiceServer) {
	// If the following call pancis, it indicates UnimplementedIpServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IpService_ServiceDesc, srv)
}

func _IpService_CreateIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpServiceServer).CreateIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpService_CreateIp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpServiceServer).CreateIp(ctx, req.(*CreateIpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpService_GetIps_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIpsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpServiceServer).GetIps(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpService_GetIps_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpServiceServer).GetIps(ctx, req.(*GetIpsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IpService_GetIp_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIpRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IpServiceServer).GetIp(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IpService_GetIp_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IpServiceServer).GetIp(ctx, req.(*GetIpRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IpService_ServiceDesc is the grpc.ServiceDesc for IpService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IpService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ip.IpService",
	HandlerType: (*IpServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateIp",
			Handler:    _IpService_CreateIp_Handler,
		},
		{
			MethodName: "GetIps",
			Handler:    _IpService_GetIps_Handler,
		},
		{
			MethodName: "GetIp",
			Handler:    _IpService_GetIp_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ip.proto",
}
